-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- https://lua.expert/
return {
	Flesh = {
		MaxHealth = 75,
		HipHeight = 1,
		PelvisDrop = 3,
		WanderSpeed = 4.5,
		FleeSpeed = 20,
		ChargeSpeed = 20,
		FlankRadius = 9,
		DetectRange = 130,
		SenseRange = 28,
		LiteSimRadius = 250,
		WanderSimRadius = 600,
		LiteWanderInterval = 1,
		RepathThreshold = 4,
		PathAgent = {
			AgentRadius = 3,
			AgentHeight = 5,
			AgentCanJump = false,
			AgentCanClimb = false,
			WaypointSpacing = 4
		},
		DetectFOV = 360,
		WanderRadius = 30,
		MeleeRange = 4,
		MeleeDamage = 18,
		MeleeCooldown = 1.5,
		AggravatedDuration = 6,
		PanicHealthFraction = 0,
		CorpseDespawn = 30,
		RespawnDelay = 45,
		GrazeChance = 0.4,
		GrazeDuration = 3,
		LookAroundChance = 0.25,
		RestAfterCalm = 25,
		RestChance = 0.3,
		RestDuration = 10,
		RestPelvisDrop = 1.17,
		WalkAnimRef = 7,
		RunAnimRef = 14,
		ThreatenDuration = 0.5,
		FlinchCooldown = 0.8,
		Animations = {
			Walk = "stand_walk_fwd_0",
			Run = "_stand_run_0",
			Death = "stand_die_0",
			Flinch = "stand_scared_0",
			RunFlinch = "stand_run_dmg_0",
			ToEat = "stand_to_eat_0",
			LookAround = "stand_look_around_0",
			Threaten = "stand_threaten_0",
			LieDown = "stand_lie_down_0",
			GetUp = "lie_stand_up_0",
			Idle = { "stand_idle_1", "stand_idle_0", "stand_idle_2" },
			Attack = { "stand_attack_1", "stand_attack_0", "stand_attack_2", "stand_attack_3" },
			RunAttack = { "stand_run_attack_0", "stand_run_attack_1", "stand_run_attack_2" },
			Graze = { "stand_eat_0", "stand_eat_1", "stand_eat_2", "stand_eat_3" },
			LieIdle = { "lie_idle_0", "lie_idle_1" },
			DeathPose = { "lie_idle_0", "lie_idle_1", "death_pose_0", "death_pose_1", "death_pose_2" }
		},
		Sounds = {
			Steps = {
				"step_flesh_1",
				"step_flesh_2",
				"step_flesh_3",
				"step_flesh_4",
				"step_flesh_5",
				"step_flesh_6",
				"step_flesh_7",
				"step_flesh_8",
				"step_flesh_9",
				"step_flesh_10"
			},
			Idle = { "flesh_idle_0", "flesh_idle_1", "flesh_idle_2", "flesh_idle_3", "flesh_idle_4" },
			Graze = { "flesh_eat_0", "flesh_eat_1", "flesh_eat_2", "flesh_eat_3", "flesh_eat_4", "flesh_eat_5" },
			Threaten = { "flesh_aggressive_0", "flesh_aggressive_1", "flesh_aggressive_2" },
			Attack = { "flesh_attack_0", "flesh_attack_1", "flesh_attack_2", "flesh_attack_3" },
			AttackHit = { "flesh_attack_hit_0", "flesh_attack_hit_1" },
			Hurt = { "flesh_pain_0", "flesh_pain_1", "flesh_pain_2", "flesh_pain_3", "flesh_pain_4" },
			Panic = { "flesh_panic_0", "flesh_panic_1", "flesh_panic_2" },
			Death = { "flesh_death_0", "flesh_death_1", "flesh_death_2", "flesh_death_3", "flesh_death_4" },
			Spawn = { "flesh_aggressive_0", "flesh_aggressive_1", "flesh_aggressive_2" }
		},
		StepIntervalRef = 9,
		StepMinInterval = 0.18,
		IdleSoundEvery = 6,
		PanicSoundEvery = 2.5,
		HurtSoundCooldown = 0.5,
		SoundMaxDistance = 150,
		SoundVolumeMult = 1.5
	},
	Spawning = {
		CheckInterval = 4,
		MinSpawnDistance = 120,
		GroundRaycastHeight = 50,
		CohesionRadius = 25,
		AnchorDriftStep = 15,
		PackSizeWeights = { 10, 35, 40, 15 },
		Defaults = {
			MutantType = "Flesh",
			Population = nil,
			RespawnInterval = 240,
			TerritoryRadius = 130
		}
	}
}