-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- https://lua.expert/
local STATES = require(game:GetService("ReplicatedStorage").Modules.DirectionalAnimation.S_Config).STATES

local function createLookupSet(p1) --[[ createLookupSet | Line: 4 ]]
	local t = {}

	for i, v in ipairs(p1) do
		t[v] = true
	end

	return t
end

local list = {
	STATES.WALK,
	STATES.WALKR,
	STATES.WALKL,
	STATES.WALKRIGHT,
	STATES.WALKLD,
	STATES.WALKLDR,
	STATES.WALKRD,
	STATES.WALKRDR
}
local list2 = {
	STATES.CROUCH_IDLE,
	STATES.CROUCH_WALK,
	STATES.CROUCH_WALKR,
	STATES.CROUCH_WALKL,
	STATES.CROUCH_WALKRIGHT,
	STATES.CROUCH_WALKLD,
	STATES.CROUCH_WALKLDR,
	STATES.CROUCH_WALKRD,
	STATES.CROUCH_WALKRDR
}
local list3 = {
	STATES.INJURED_WALK,
	STATES.INJURED_WALKR,
	STATES.INJURED_WALKL,
	STATES.INJURED_WALKRIGHT,
	STATES.INJURED_WALKLD,
	STATES.INJURED_WALKLDR,
	STATES.INJURED_WALKRD,
	STATES.INJURED_WALKRDR
}
local list4 = {
	STATES.WALKLD,
	STATES.WALKLDR,
	STATES.WALKRD,
	STATES.WALKRDR,
	STATES.CROUCH_WALKLD,
	STATES.CROUCH_WALKLDR,
	STATES.CROUCH_WALKRD,
	STATES.CROUCH_WALKRDR,
	STATES.INJURED_WALKLD,
	STATES.INJURED_WALKLDR,
	STATES.INJURED_WALKRD,
	STATES.INJURED_WALKRDR
}
local t = {
	STATES = STATES,
	WALK_STATES = list,
	CROUCH_STATES = list2,
	INJURED_STATES = list3,
	DIAGONAL_STATES = list4,
	WALK_TO_CROUCH = {
		[STATES.IDLE] = STATES.CROUCH_IDLE,
		[STATES.WALK] = STATES.CROUCH_WALK,
		[STATES.WALKR] = STATES.CROUCH_WALKR,
		[STATES.WALKL] = STATES.CROUCH_WALKL,
		[STATES.WALKRIGHT] = STATES.CROUCH_WALKRIGHT,
		[STATES.WALKLD] = STATES.CROUCH_WALKLD,
		[STATES.WALKLDR] = STATES.CROUCH_WALKLDR,
		[STATES.WALKRD] = STATES.CROUCH_WALKRD,
		[STATES.WALKRDR] = STATES.CROUCH_WALKRDR
	},
	WALK_TO_INJURED = {
		[STATES.WALK] = STATES.INJURED_WALK,
		[STATES.WALKR] = STATES.INJURED_WALKR,
		[STATES.WALKL] = STATES.INJURED_WALKL,
		[STATES.WALKRIGHT] = STATES.INJURED_WALKRIGHT,
		[STATES.WALKLD] = STATES.INJURED_WALKLD,
		[STATES.WALKLDR] = STATES.INJURED_WALKLDR,
		[STATES.WALKRD] = STATES.INJURED_WALKRD,
		[STATES.WALKRDR] = STATES.INJURED_WALKRDR
	}
}
local t2 = {}

for i, v in ipairs(list) do
	t2[v] = true
end

t.WALK_STATE_SET = t2

local t3 = {}

for i, v in ipairs(list2) do
	t3[v] = true
end

t.CROUCH_STATE_SET = t3

local t4 = {}

for i, v in ipairs(list3) do
	t4[v] = true
end

t.INJURED_STATE_SET = t4

local t5 = {}

for i, v in ipairs(list4) do
	t5[v] = true
end

t.DIAGONAL_STATE_SET = t5

return t