-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- https://lua.expert/
local t = {}
local StateConstants = require(script.Parent.StateConstants)
local S_Config = require(game:GetService("ReplicatedStorage").Modules.DirectionalAnimation.S_Config)
local STATES = StateConstants.STATES
local TRANSITION_TIMES = S_Config.TRANSITION_TIMES

function t.new() --[[ new | Line: 7 | Upvalues: t (copy) ]]
	local v1 = setmetatable({}, {
		__index = t
	})

	v1.transitions = v1:_buildTransitionTable()

	return v1
end
function t._buildTransitionTable(p1) --[[ _buildTransitionTable | Line: 13 | Upvalues: STATES (copy), TRANSITION_TIMES (copy) ]]
	return {
		[STATES.WALKR] = {
			[STATES.WALK] = TRANSITION_TIMES.WALK_TO_REVERSE
		},
		[STATES.WALK] = {
			[STATES.WALKR] = TRANSITION_TIMES.REVERSE_TO_WALK,
			[STATES.WALKLD] = TRANSITION_TIMES.WALK_TO_LEFT_DIAG,
			[STATES.WALKRD] = TRANSITION_TIMES.WALK_TO_RIGHT_DIAG
		},
		[STATES.WALKL] = {
			[STATES.WALK] = TRANSITION_TIMES.WALK_TO_LEFT,
			[STATES.WALKRIGHT] = TRANSITION_TIMES.RIGHT_TO_LEFT,
			[STATES.IDLE] = TRANSITION_TIMES.LEFT_TO_IDLE,
			[STATES.WALKLD] = TRANSITION_TIMES.WALK_TO_LEFT_DIAG,
			[STATES.WALKLDR] = TRANSITION_TIMES.WALK_TO_LEFT_DIAG
		},
		[STATES.WALKRIGHT] = {
			[STATES.WALK] = TRANSITION_TIMES.WALK_TO_RIGHT,
			[STATES.WALKL] = TRANSITION_TIMES.LEFT_TO_RIGHT,
			[STATES.IDLE] = TRANSITION_TIMES.RIGHT_TO_IDLE,
			[STATES.WALKRD] = TRANSITION_TIMES.WALK_TO_RIGHT_DIAG,
			[STATES.WALKRDR] = TRANSITION_TIMES.WALK_TO_RIGHT_DIAG
		},
		[STATES.WALKLD] = {
			[STATES.WALK] = TRANSITION_TIMES.LEFT_DIAG_TO_WALK,
			[STATES.WALKRD] = TRANSITION_TIMES.LEFT_DIAG_TO_RIGHT_DIAG,
			[STATES.WALKLDR] = TRANSITION_TIMES.LEFT_DIAG_TO_LEFT_DIAG_REV,
			[STATES.WALKL] = TRANSITION_TIMES.LEFT_DIAG_TO_WALK,
			[STATES.IDLE] = TRANSITION_TIMES.DIAG_TO_IDLE
		},
		[STATES.WALKLDR] = {
			[STATES.WALKLD] = TRANSITION_TIMES.LEFT_DIAG_REV_TO_LEFT_DIAG,
			[STATES.WALKRDR] = TRANSITION_TIMES.LEFT_DIAG_TO_RIGHT_DIAG,
			[STATES.WALKL] = TRANSITION_TIMES.LEFT_DIAG_TO_WALK,
			[STATES.IDLE] = TRANSITION_TIMES.DIAG_TO_IDLE
		},
		[STATES.WALKRD] = {
			[STATES.WALK] = TRANSITION_TIMES.RIGHT_DIAG_TO_WALK,
			[STATES.WALKLD] = TRANSITION_TIMES.RIGHT_DIAG_TO_LEFT_DIAG,
			[STATES.WALKRDR] = TRANSITION_TIMES.RIGHT_DIAG_TO_RIGHT_DIAG_REV,
			[STATES.WALKRIGHT] = TRANSITION_TIMES.RIGHT_DIAG_TO_WALK,
			[STATES.IDLE] = TRANSITION_TIMES.DIAG_TO_IDLE
		},
		[STATES.WALKRDR] = {
			[STATES.WALKRD] = TRANSITION_TIMES.RIGHT_DIAG_REV_TO_RIGHT_DIAG,
			[STATES.WALKLDR] = TRANSITION_TIMES.RIGHT_DIAG_TO_LEFT_DIAG,
			[STATES.WALKRIGHT] = TRANSITION_TIMES.RIGHT_DIAG_TO_WALK,
			[STATES.IDLE] = TRANSITION_TIMES.DIAG_TO_IDLE
		},
		[STATES.IDLE] = {
			[STATES.WALKL] = TRANSITION_TIMES.LEFT_TO_IDLE,
			[STATES.WALKRIGHT] = TRANSITION_TIMES.RIGHT_TO_IDLE,
			[STATES.WALKLD] = TRANSITION_TIMES.IDLE_TO_DIAG,
			[STATES.WALKLDR] = TRANSITION_TIMES.IDLE_TO_DIAG,
			[STATES.WALKRD] = TRANSITION_TIMES.IDLE_TO_DIAG,
			[STATES.WALKRDR] = TRANSITION_TIMES.IDLE_TO_DIAG
		}
	}
end
function t.getTransitionTime(p1, p2, p3) --[[ getTransitionTime | Line: 34 ]]
	local v1 = p1.transitions[p2]

	if v1 and v1[p3] then
		return v1[p3]
	end

	return p1:_calculateDynamicTransition(p2, p3)
end
function t._calculateDynamicTransition(p1, p2, p3) --[[ _calculateDynamicTransition | Line: 42 | Upvalues: StateConstants (copy), TRANSITION_TIMES (copy), STATES (copy) ]]
	local v1 = StateConstants.DIAGONAL_STATE_SET[p2]
	local v2 = StateConstants.DIAGONAL_STATE_SET[p3]

	if v1 or v2 then
		if v1 and v2 then
			return TRANSITION_TIMES.LEFT_DIAG_TO_RIGHT_DIAG * 0.7
		end

		if v1 then
			return TRANSITION_TIMES.IDLE_TO_DIAG
		end

		return TRANSITION_TIMES.DIAG_TO_IDLE
	end

	local _ = StateConstants.WALK_STATE_SET[p2] and p3 == STATES.IDLE

	return TRANSITION_TIMES.IDLE_TO_WALK
end

return t