-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- https://lua.expert/
local t = {
	gibbing = false,
	thirdPersonFiring = false,
	arcadeBullets = false,
	leaderboard = true,
	rblxDamageTags = true,
	systemChat = true,
	deathScreen = true,
	fallDamage = true,
	fallDamageDist = 19,
	fallDamageMultiplier = 3,
	teamKill = false,
	teamTracers = false,
	firstPersonBody = true,
	headRotation = true,
	headRotationSpeed = 15,
	disableHeadRotation = false,
	headRotationEventRate = 0.5,
	replicatedHeadRotationSpeed = 0.6,
	useDeathCameraSubject = true,
	explosionRaycast = true,
	lockFirstPerson = true,
	gunDropping = false,
	dropOnDeath = false,
	dropOnLeave = false,
	dropDespawnTime = 60,
	maxDroppedGuns = 15,
	pickupDistance = 7,
	dropGunAnchorTime = 3,
	walkSpeed = 10,
	sprintSpeed = 16,
	crouchSpeed = 6,
	proneSpeed = 3,
	movementLeaning = true,
	replicateMovementLeaning = true,
	maxLeanAngle = 5,
	stanceChangeTime = 0.3,
	canLean = true,
	canCrouch = true,
	canProne = true,
	proneAngle = true,
	jumpCooldown = 2,
	proceduralAimAnim = true,
	keySprint = { Enum.KeyCode.LeftShift, Enum.KeyCode.ButtonL3 },
	keyReload = { Enum.KeyCode.R, Enum.KeyCode.ButtonX },
	keyChamber = { Enum.KeyCode.F },
	sightSwitch = { Enum.KeyCode.T },
	freeLook = { Enum.UserInputType.MouseButton3 },
	lowerStance = { Enum.KeyCode.C },
	raiseStance = { Enum.KeyCode.X },
	holdUp = { Enum.KeyCode.U },
	holdPatrol = { Enum.KeyCode.N },
	holdDown = { Enum.KeyCode.M },
	switchFireMode = { Enum.KeyCode.V },
	leanLeft = { Enum.KeyCode.Q },
	leanRight = { Enum.KeyCode.E },
	dropKey = { Enum.KeyCode.Backspace, Enum.KeyCode.ButtonB },
	pickupKey = { Enum.KeyCode.G },
	toggleLaser = { Enum.KeyCode.J },
	toggleFlashlight = { Enum.KeyCode.H },
	ToggleBipod = { Enum.KeyCode.B },
	holdForScrollZoom = Enum.KeyCode.L,
	fireGun = { Enum.UserInputType.MouseButton1, Enum.KeyCode.ButtonR2 },
	aimGun = { Enum.UserInputType.MouseButton2, Enum.KeyCode.ButtonL2 },
	defaultAimSensitivity = 0.4,
	gunInputPriority = 100,
	movementInputPriority = 100,
	mobileButtons = true,
	toggleAiming = false,
	animDistance = 1000,
	fireEffectDistance = 4000,
	maxBulletDistance = 6000,
	maxHitDistance = 1000,
	ragdolls = true,
	bodyDespawn = 60,
	bodyLimit = 15,
	bodyAnchorTime = 10,
	shellEjection = true,
	shellDistance = 50,
	shellMaxCount = 30,
	shellDespawn = 10,
	shellAnchorTime = 3,
	firstPersonHolsters = false,
	blurEffects = false,
	despawnEmptyAmmoBoxes = true,
	ammoBoxDespawnTime = 10,
	maxBullets = 500,
	bulletHoles = true,
	bulletHoleDespawnTime = 20,
	glassShatter = true,
	glassShardDespawnTime = 20,
	glassRespawnTime = 60
}

t.bulletAcceleration = Vector3.new(0, -workspace.Gravity, 0)
t.useBulletForce = true
t.bulletPen = true
t.breathingSpeed = 5
t.breathingDist = 0.02
t.breathingAimMultiplier = 0.15
t.bobSpeed = 10
t.bobDampening = 14
t.aimBobDampening = 2.5
t.cameraMovement = false
t.cameraBobDampening = 1
t.cameraTilting = false
t.cameraLimitInSeats = true
t.hipfireMove = true
t.hipfireMoveX = 15
t.hipfireMoveY = 10
t.hipfireMoveSpeed = 0.05
t.offCenterAiming = false
t.pushBackViewmodel = true
t.raiseGunAtWall = true
t.fireWithFreelook = false
t.maxStrafeRoll = 10
t.showAccessoriesFP = true
t.lowHealthEffects = true
t.suppressionEffects = true
t.footstepSounds = true
t.tracerStartDistance = 15
t.fireSoundVariation = 500
t.firstPersonEcho = true
t.laserTrail = false
t.destructibleObjects = true
t.destructibleDespawnTime = 30
t.disablePlayerDebrisCollision = true
t.listenForKillAll = false
t.multiKillThreshold = 2
t.printKillLogs = false
t.requireEquippedGun = false
t.listenForExplosionSpam = false
t.ammoCountCheck = false
t.listenForReloadSpam = false
t.killAngleCheck = false
t.multiKillDistanceCheck = false
t.strikes = false
t.maxStrike = 3
t.serverBanList = false
t.angleMultipler = 5
t.aimingDivider = 50
t.maximumAngle = 10
t.swaySmoothness = 0.07
t.reloadLockSeconds = 6
t.version = "v1.2.3"

return t