-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- https://lua.expert/
return {
	["6Sh118 Green"] = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 16000,
		Description = "Russian military large assault pack. Heavy but massive capacity for extended missions.",
		ImageID = "rbxassetid://130348804030029",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "6Sh118 Green",
		Name = "6Sh118 Green",
		Weight = 4,
		WeightBonus = 20,
		BackgroundColor = Color3.fromRGB(30, 40, 25),
		Size = Vector2.new(4, 5),
		SlotSize = Vector2.new(5, 8)
	},
	AssaultBag = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 6000,
		Description = "Lightweight assault bag for quick raids. Compact but versatile.",
		ImageID = "rbxassetid://83188522160370",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "AssaultBag",
		Name = "Assault Bag",
		Weight = 1,
		WeightBonus = 6,
		BackgroundColor = Color3.fromRGB(35, 35, 30),
		Size = Vector2.new(2, 4),
		SlotSize = Vector2.new(4, 4)
	},
	["Attack 2 Raid Backpack"] = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 14000,
		Description = "Mid-sized tactical raid pack. Durable and organized with good carrying capacity.",
		ImageID = "rbxassetid://109221133242248",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "Attack 2 Raid Backpack",
		Name = "Attack 2 Raid Backpack",
		Weight = 2.5,
		WeightBonus = 14,
		BackgroundColor = Color3.fromRGB(30, 30, 30),
		Size = Vector2.new(3, 5),
		SlotSize = Vector2.new(5, 6)
	},
	Backpack = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 8000,
		ImageID = "rbxassetid://126155841672494",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "Backpack",
		Name = "Backpack",
		Weight = 1.5,
		WeightBonus = 10,
		BackgroundColor = Color3.fromRGB(35, 25, 38),
		Size = Vector2.new(2, 5),
		SlotSize = Vector2.new(5, 4)
	},
	ImprovisedBackpack = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 25,
		Description = "Crudely constructed rucksack made from scrap canvas and rope. Small capacity but light.",
		ImageID = "rbxassetid://129715310529998",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "ImprovisedBackpack",
		Name = "Improvised Backpack",
		Weight = 0.8,
		WeightBonus = 4,
		BackgroundColor = Color3.fromRGB(45, 35, 25),
		Size = Vector2.new(2, 3),
		SlotSize = Vector2.new(3, 4)
	},
	SovietBackpack = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 9000,
		Description = "Standard Soviet-issue rucksack. Rugged canvas construction, moderate capacity.",
		ImageID = "rbxassetid://108831309934257",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "SovietBackpack",
		Name = "Soviet Backpack",
		Weight = 1.5,
		WeightBonus = 8,
		BackgroundColor = Color3.fromRGB(40, 35, 25),
		Size = Vector2.new(3, 4),
		SlotSize = Vector2.new(4, 6)
	},
	["ALICE FIELD PACK"] = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 12500,
		Description = "US Army ALICE field pack. Cold War-era nylon ruck with external frame, durable and deep.",
		ImageID = "rbxassetid://118214864441845",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "ALICE FIELD PACK",
		Name = "ALICE Field Pack",
		Weight = 2.2,
		WeightBonus = 12,
		BackgroundColor = Color3.fromRGB(40, 45, 30),
		Size = Vector2.new(3, 4),
		SlotSize = Vector2.new(5, 5)
	},
	["Hiking Backpack"] = {
		AttachTo = "Torso",
		BackgroundTransparency = 0.8,
		BaseSellValue = 7000,
		Description = "Civilian hiking pack with padded straps. Lighter than military rucks for comparable capacity.",
		ImageID = "rbxassetid://98539964366436",
		ItemType = "Backpack",
		LootCategory = "Gear",
		Model = "Hiking Backpack",
		Name = "Hiking Backpack",
		Weight = 1.6,
		WeightBonus = 9,
		BackgroundColor = Color3.fromRGB(35, 50, 60),
		Size = Vector2.new(2, 5),
		SlotSize = Vector2.new(4, 5)
	}
}